language: python
python: 3.8

dist: xenial    # required for Python 3.7 (travis-ci/travis-ci#9069)
sudo: required  # required for Python 3.7 (travis-ci/travis-ci#9069)

addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python3.6
      - python3.7
      - python3.8

install:
  - pip install tox

script:
  - tox

notifications:
  email:
    on_success: never
    on_failure: always